[at_school]
hsjc = 1
xasymt = 1
actionType = "addRbxx"
userLoginId = "1145141919" # 学号
szcsbm = 1
bdzt = 1
szcsmc = "在学校"
sfyzz = 0
sfqz = "0"
tbly = "sso"
qtqksm = "无"
ycqksm = ""
userType = 2
userName = "田所" # 姓名
