[basic]
username = "1145141919" # 改成你的用户名，学号/手机号/邮箱/身份证号都可
password = "998244353" # 改成你的密码

[report.other]
hsjc = 1
actionType = "addRbxx"
userLoginId = "1145141919" # 改成你的学号
szcsbm = 610116 # 改成你的地址的地区编码，也就是该地区的身份证号前 6 位
bdzt = 1
szcsmc = "下北泽" # 改成你的地址
sfyzz = 0
sfqz = "0"
tbly = "sso"
qtqksm = "无"
ycqksm = ""
userType = 2
userName = "田所" # 改成你的姓名
sfczbcqca = ""
czbcqcasjd = ""
sfczbcfhyy = ""
czbcfhyysjd = ""
szcsmc1 = "下北泽" # 改成你的地址
sfjt = 0
sfjtsm = ""
sfjcry = 0
sfjcrysm = ""
sfjcqz = 0
sfjcqzsm = ""
glqk = 0
glksrq = ""
gljsrq = ""
glyy = ""
sfjkqk = 0
jkqksm = ""
sfmtbg = ""
qrlxzt = 3
xymc = "信息类" # 改成你的学院
xssjhm = "13888888888" # 改成你的手机号码
